#!/bin/sh

source do_setup.sh

python3 run_ner.py \
    --do_train=true \
    --do_eval=true \
    --vocab_file="$biobert_dir"/vocab.txt \
    --bert_config_file="$biobert_dir"/bert_config.json \
    --init_checkpoint="$biobert_dir"/biobert_model.ckpt \
    --num_train_epochs=10.0 \
    --data_dir="$ner_dir/" \
    --output_dir="$out_dir"

./do_detokenize.sh
perl biocodes/conlleval.pl < "$out_dir"/NER_result_conll.txt
